# image: $CI_REGISTRY_IMAGE/taste:latest
image: taste-buster:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - post_build

build:
  stage: build
  script:
    - ./gitlabci-test.sh
  artifacts:
    paths:
      - 'kazoo/test/logs/*.err.txt'
      - 'opengeode/tests/testsuite/logs/*.err.txt'
    when: on_failure
    expire_in: 2 weeks
